name: Release new plugin version
on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]
jobs:
  web-deploy:
    name: 🎉 Deploy to development server
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🛠 Building ZIP file
        run: |
          zip -r prikr-image-offloader.zip . -x ".git/*" ".github/*" ".gitignore"

      - name: 📂 Sync files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ vars.PRIKR_IP }}
          remote-user: ${{ vars.SSH_USERNAME }}
          private-ssh-key: ${{ secrets.PRIVATE_RSA_KEY }}
          ssh-port: ${{ vars.PRIKR_PORT }}
          destination-path: ~/home/prikr/domains/prikr.io/public_html/plugin/prikr-image-offloader/
          rsync-options: --delete-after --recursive --itemize-changes --exclude=* --include=prikr-image-offloader.zip --include=info.json
